# Name your project! Use only lowercase letters and underscores.
# The project name usually reflects your organization or purpose.
name: 'dbt_analytics'

# Version of your dbt project.
version: '1.0.0'

# Specifies which dbt profile to use for connection settings.
profile: 'dbt_analytics'

# Paths where dbt will look for different types of files.
model-paths: ["models"]          # Where SQL models are stored
analysis-paths: ["analyses"]     # Where analysis files are stored
test-paths: ["tests"]            # Where test files are stored
seed-paths: ["seeds"]            # Where CSV seed files are stored
macro-paths: ["macros"]          # Where reusable macros are stored
snapshot-paths: ["snapshots"]    # Where snapshot files are stored

# Directories cleaned by `dbt clean` command.
clean-targets:
  - "target"                    # Compiled SQL and build artifacts
  - "dbt_packages"              # Installed dbt packages

# Model configurations: apply settings to groups of models.
models:
  dbt_analytics:                # Project folder name
    staging:                    # Sub-folder for staging models
      +materialized: view       # Build all staging models as views
      snowflake_warehouse: dbt_wh  # Use this Snowflake warehouse for staging
    marts:                     # Sub-folder for marts models
      +materialized: table     # Build all marts models as tables
      snowflake_warehouse: dbt_wh  # Use this Snowflake warehouse for marts